Suppress newly introduced build error (added `-Wno-error=shadow` flag)
We get following error because of the change:

```
error: declaration of 'const tflite::ArithmeticParams& params' shadows a parameter [-Werror=shadow]
```

Added `-Wno-error=shadow` compiler flag to treat this as a warning and not error.

Signed-off-by: Vikram Dattu <vikram.dattu@espressif.com>